# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rishav
email: rishkumar2345@gmail.com
description: > # this means to ignore newlines until "baseurl:" # the subpath of your site, e.g. /blog
url: "http://rish-av.github.io" # the base hostname & protocol for your site
twitter_username: rishav_real 
github_username:  rish-av

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-171076140-1
disqus_shortname: rish-av-github-io

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
