---
title: "about"
---
I'm a graduate student at [Mila](https://mila.quebec/en), broadly interested in building reliable machine learning systems that work at scale. At Mila, my research has focused on topics in RL, mainly offline (explainability and adaptive regularization), real-time RL, and benchmarking SSL methods for Atari games.

My larger goal is to develop safe, interpretable, real-time, and sample-efficient agents, motivating my interests in areas like mechanistic interpretability, world models, and real-time systems.

Before Mila, I co-founded [Offside](https://pitchbook.com/profiles/company/539173-27) (scaled to 100k users), spent ~2 years at [DFKI](http://dfki.de) in Germany developing real-time vision algorithms for precision farming ([blog post](https://rish-av.github.io/blog/2024/spotspraying/)), and earned a BEng (Thesis) in Computer Science from [BITS Pilani](https://bits-pilani.ac.in/) in 2020.

## Beyond Research

Outside of research, I enjoy reading about ancient civilizations, listening to classic rock, trekking, and strength training. I also write blogs reflecting on projects and life learnings. Check them out [here](https://rish-av.github.io/blog/).